kind: pipeline
type: docker
name: build

steps:
  - name: safety
    image: pyupio/safety
    commands:
      - safety check --file builder/requirements.txt --ignore 70612

  - name: markdown lint
    image: tmknom/markdownlint
    commands:
      - sh /home/nonroot/entrypoint.sh posts

  - name: spellcheck
    image: ghcr.io/streetsidesoftware/cspell:latest
    commands:
      - /app/index.js --no-progress --show-context --language-id markdown --no-color --locale en 'posts/*/content.md'

  - name: build&publish
    image: python:3.11
    environment:
      INCLUDE_UNPUBLISHED: 0
      OUTPUT_MODULE: webploy
      OUTPUT_WEBPLOY_SITE: "blog.marcsello.com"
      OUTPUT_WEBPLOY_URL:
        from_secret: WEBPLOY_URL
      OUTPUT_WEBPLOY_USER:
        from_secret: WEBPLOY_USER
      OUTPUT_WEBPLOY_PASSWORD:
        from_secret: WEBPLOY_PASSWORD
    commands:
      - pip3 install -r builder/requirements.txt
      - 'OUTPUT_WEBPLOY_META="${DRONE_BUILD_NUMBER}" python3 -m builder'
    when:
      branch:
        - main

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CHAT_ID
    when:
      status: [ failure ]
