# MD013/line-length - Line length
MD013: false


# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
# we use a separate title field in the meta for this
MD041: false

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  # Punctuation characters
  punctuation: ".,;:。，；：！" # <- allowed exclamation mark

MD033:
  allowed_elements:
    - "big"
